modLoader = "javafml"
loaderVersion = "[47,)" # Подходит для Forge 1.20.1
license = "All Rights Reserved"

[[mods]]
modId = "bindon"
version = "1.0.1"
displayName = "BindOn"
displayURL = "https://github.com/Netlifex/bindon"
authors = "Netlifex"
logoFile="bindon.png"

description = '''
BindOn is a Minecraft Forge mod for 1.20.1 that lets the server simulate key presses (F1, F5, W, Shift, etc.) for players using commands.
It’s useful for adventure maps, cutscenes, and admin control.

Features:
- Trigger any keyboard key remotely via command
- Full support for @a, @p, player selectors
- Simple syntax: /bindon <key> <player>
'''

[[dependencies."bindon"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."bindon"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
